# Generated by Django 3.1.7 on 2021-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(default='NG', max_length=100)),
            ],
        ),
    ]
